baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Susilowati's Blog"
  subtitle    = "Welcome!"

  cover       = "uploads/HEADER.jpg"
  description = "It could be everything"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  
  githubName = "Susilowati12"

  logo = ""
  orgName = "DM"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  author = "Susilowati"
  authorAvatar = "uploads/profile_picture.jpeg"
  authorLocation = "Karawang, ID"
  authorWebsite = "https://github.com/Susilowati12"
  authorDescription = "A Student"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"
  Authors = "/:slug/"
  Pages = "/:slug/"
  Homepage = "/:slug/"


[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "My Life"
  url = "/tags/life/"
  weight = 100

[[menu.main]]
  name = "Media"
  url = "/categories/anything/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95
